FROM python:3.11-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN python manage.py --upgrade pip 

RUN pip install -r requirements.txt
COPY . .

RUN python manage.py collectstatic --noinput || true

CMD ["gunicorn","cors.wsgi:application",'--bind','0.0.0.0:8000','--workers','3']